name: Super-Linter

on:
  push:
    paths:
      - README.md
  pull_request:
    paths:
      - README.md
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  super-lint:
    name: Lint README.md
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Super-Linter for README.md
        uses: github/super-linter@v4
        with:
          files: README.md
        env:
          DEFAULT_BRANCH: temp-jenkins2
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
